import type { NextPage } from 'next'
import Head from 'next/head'
import MyButton from '../components/MyButton/MyButton'
import 'bootstrap/dist/css/bootstrap.css'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Payproff Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MyButton />
    </div>
  )
}

export default Home
